<?php
$CEIR_TABLES = [
  'kotwali'           => 'ceir_kotwali',
  'industrial_area'   => 'ceir_industrial_area',
  'bank_note_press'   => 'ceir_bank_note_press',
  'civil_line'        => 'ceir_civil_line',
  'nahar_darwaja'     => 'ceir_nahar_darwaja',
  'vijayganj_mandi'   => 'ceir_vijayganj_mandi',
  'sonkatch'          => 'ceir_sonkatch',
  'pipalrawan'        => 'ceir_pipalrawan',
  'bhaurasa'          => 'ceir_bhaurasa',
  'tonkkhurd'         => 'ceir_tonkkhurd',
  'bagli'             => 'ceir_bagli',
  'hatpiplya'         => 'ceir_hatpiplya',
  'barotha'           => 'ceir_barotha',
  'udai_nagar'        => 'ceir_udai_nagar',
  'khategaon'         => 'ceir_khategaon',
  'kannod'            => 'ceir_kannod',
  'kantaphod'         => 'ceir_kantaphod',
  'nemawar'           => 'ceir_nemawar',
  'harangaon'         => 'ceir_harangaon',
  'satwas'            => 'ceir_satwas',
  'kamlapur'          => 'ceir_kamlapur',
];
